export TT_METAL_BASE=/workspaces/tensix/tt-metal
export TT_UMD_SIMULATOR=$TT_METAL_BASE/sim/libttsim.so
export TT_METAL_SIMULATOR=$TT_METAL_BASE/sim/libttsim.so
export TT_METAL_SLOW_DISPATCH_MODE=1
export TT_UMD_TTSIM_SLOW_PATH=1
export TT_LOGGER_LEVEL=info
export TT_METAL_LOG_KERNELS_COMPILE_COMMANDS=1
export TT_METAL_KERNEL_MAP=0

export TT_METAL_RISCV_DEBUG_INFO=1
export TT_METAL_WATCHER=1
export TT_METAL_WATCHER_CORES='all'
export TT_METAL_DPRINT_CORES="(0,0),(0,1)"
#export TT_METAL_DPRINT_ONE_FILE_PER_RISC=0
export TT_METAL_DPRINT_FILE=$TT_METAL_BASE/generated/dprint/dprint.log
export PYTHONPATH=$TT_METAL_BASE/../tt-forge
unset LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$TT_METAL_BASE/build_Release/tt_metal:$TT_METAL_BASE/build_Release/ttnn:$TT_METAL_BASE/build_Release/lib:${LD_LIBRARY_PATH:-}

export TT_METAL_DEVICE_PROFILER=1
export TT_METAL_DEVICE_PROFILER_NOC_EVENTS=1
export TT_METAL_DEVICE_PROFILER_NOC_EVENTS_RPT_PATH=$TT_METAL_BASE/profiler_out
export TT_METAL_DISABLE_SFPLOADMACRO=1
export TT_SIM_USE_NATIVE_NOC_MULTICAST_WRITE=0
export TT_METAL_FORCE_JIT_COMPILE=1
export HF_ENDPOINT=https://hf-mirror.com
#unset TT_UMD_TTSIM_SLOW_PATH
#unset TT_METAL_SLOW_DISPATCH_MODE
unset TT_METAL_WATCHER //unset watcher, wather will enble noc saniter check, this will slow down performance significatlly
unset TT_METAL_WATCHER_CORES

unset TT_METAL_DPRINT_CORES
unset TT_METAL_DEVICE_PROFILER
unset TT_METAL_DEVICE_PROFILER_NOC_EVENTS
unset TT_METAL_DEVICE_PROFILER_NOC_EVENTS_RPT_PATH
unset TT_METAL_KERNEL_MAP
unset TT_METAL_RISCV_DEBUG_INFO
unset TT_METAL_FORCE_JIT_COMPILE
unset TT_METAL_LOG_KERNELS_COMPILE_COMMANDS

export OPENVLA_WEIGHTS=/root/openvla_weights
